---
# installing httpd package
- name: install apache Redhat version
  yum:
   name: httpd
   state: latest 
  when: ansible_os_family == "RedHat"

- name: install apache Debian version
  package:
   name: apache2
   state: latest
  when: ansible_os_family == "Debian"
     
