---

- name: "Include OS specific Variables"
  include_vars: "default.yml"

- name: "Installing Etcd package"
  package:
    name: etcd
    state: present
  
- name: "Enable and start the service"
  service:
    name: etcd
    state: started
    enabled: yes

- name: "Copy Etcd configuration file"
  template:
    src: files/etcd.conf.j2
    dest: /etc/etcd/etcd.conf
  notify: restart etcd
