---
# Configuring tomcat-users.xml
- name: tomcat-users.xml configure
  #copy:
  template:
   src: "files/tomcat-users.xml.j2"
   dest: /etc/tomcat/tomcat-users.xml
  notify: 
   - restart tomcat service
