---
# Starting tomcat service
- name: start tomcat service
  service:
   name: tomcat
   state: started
  when: ansible_os_family == "RedHat"

- name: start tomcat service
  service:
   name: tomcat7
   state: started
  when: ansible_os_family == "Debian"
